### ISSUE TITLE
Is it possible to change the trigger to a button within an item (li)? 

### ISSUE THREAD

**Issue by Chrisedmo** [Goldinteractive/jQuery.GI.TheWall.js#7]
Hey - love your script! 

But i have my code set up so that within each li, is an profile pic an some links to email etc then a button which I would like to make the expand happen. However atm if you click anywhere on the li it, it expands to show more. Is there a way to specify what will trigger the expand?

Many thanks

**Comment by GianlucaGuarini** [comment]
Thanks but I don't really understand what you are trying to do... could you make a jsfiddle?

**Comment by GianlucaGuarini** [comment]
Probably the easiest solution in your case would be to simply replace the event handler https://github.com/Goldinteractive/jQuery.GI.TheWall.js/blob/master/jQuery.GI.TheWall.js#L650

**Comment by Chrisedmo** [comment]
Thanks for the quick feedback! I just tried changing this to an ID that I have on my "find out more" button. But I get the following error _"[Error] TypeError: undefined is not an object (evaluating 'this.selectedLiData.offset.top')_ I am working up a JSFiddle to try and explain a little more.

**Comment by Chrisedmo** [comment]
Here is a quick link of what i am trying to do: http://jsfiddle.net/t03c6prw/ I want the button to only trigger the extra information… at the moment I am unable to click the email address…

**Comment by GianlucaGuarini** [comment]
http://jsfiddle.net/gianlucaguarini/q3mncvam/1/ use the custom jQuery.GI.TheWall.js I've used in the jsfiddle

**Comment by Chrisedmo** [comment]
Wow @GianlucaGuarini thank you very much! 🍻
